<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>MemorySecurIT</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Forms\MenuForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\GameForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Forms\OptionsForm.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
  <None Update="Assets\Images\*.*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>

</Project>